### ISSUE TITLE
Calibrate - IndexError: list index out of range

### ISSUE THREAD

**Issue by biesbjerg** [m4rkw/minotaur#11]
[midas@localhost ~]$ sudo -u minotaur minotaur --calibrate 0 nicehash excavator equihash eu --overwrite --force

info:      device id: 0
info:           pool: nicehash
info:   device class: 1080ti_calibrate
info: device profile: 1080ti_oc_equihash
info:          miner: excavator
info:      algorithm: equihash
info:         region: eu
info: device 0 [1080ti_calibrate]: terminating existing worker
info: device 0 [1080ti_calibrate]: max power limit: 300 W
info: device 0 [1080ti_calibrate]: stabilisation tolerance: 0.50%
info: device 0 [1080ti_calibrate]: starting warmup cycle at max power limit [timeout=10mins]
info: device 0 [1080ti_calibrate]: hashrate: 621.28 H/s
^@info: device 0 [1080ti_calibrate]: hashrate: 729.88 H/s (variance 17.48%)
Traceback (most recent call last):
  File "/home/mock/rpmbuild/BUILD/minotaur-0.9.8.8/minotaur.py", line 983, in <module>
  File "/home/mock/rpmbuild/BUILD/minotaur-0.9.8.8/minotaur.py", line 617, in calibrate
  File "/home/mock/rpmbuild/BUILD/minotaur-0.9.8.8/calibrate.py", line 128, in start
  File "/home/mock/rpmbuild/BUILD/minotaur-0.9.8.8/calibrate.py", line 258, in get_max_hashrate_and_power_draw
IndexError: list index out of range

**Comment by m4rkw** [comment]
this seems to be because the worker was stopped by an external process. i've pushed a change to catch this and exit more gracefully, will be merged in the next release.
