### ISSUE TITLE
Error when calibrating a disabled miner

### ISSUE THREAD

**Issue by biesbjerg** [m4rkw/minotaur#12]
If you have disabled a miner i minotaur.conf (for example ccminer2) it is still possible to start calibration, but it exits with an error:

```
bash-4.2$ minotaur --calibrate 1 nicehash ccminer2 x11gost eu --overwrite --force

------------------------------------------------------------------------------------
info: PLEASE NOTE: this process will not automatically overclock your card unless
info: you have enabled overclocking and configured a device profile with overclock
info: settings. You and you alone are responsible for any overclock settings that
info: you want to run this benchmark process with. We do not advise overclocking
info: and are not responsible for any hardware damage that may occur when using
info: this tool.
------------------------------------------------------------------------------------

info:      device id: 1
info:           pool: nicehash
info:   device class: 1080Ti
info: device profile: 1080ti_oc
info:          miner: ccminer2
info:      algorithm: x11gost
info:         region: eu
info: device 1 [1080Ti]: terminating existing worker

  Attribute 'GPUGraphicsClockOffset' (localhost.localdomain:0[gpu:1]) assigned value 0.


  Attribute 'GPUMemoryTransferRateOffset' (localhost.localdomain:0[gpu:1]) assigned value 0.

Power limit for GPU 00000000:03:00.0 was set to 250.00 W from 277.00 W.

Warning: persistence mode is disabled on this device. This settings will go back to default as soon as driver unloads (e.g. last application like nvidia-smi or cuda application terminates). Run with [--help | -h] switch to get more information on how to enable persistence mode.

All done.
info: device 1 [1080Ti]: max power limit: 300 W
info: device 1 [1080Ti]: stabilisation tolerance: 0.50%

  Attribute 'GPUGraphicsClockOffset' (localhost.localdomain:0[gpu:1]) assigned value 0.


  Attribute 'GPUMemoryTransferRateOffset' (localhost.localdomain:0[gpu:1]) assigned value 0.

Power limit for GPU 00000000:03:00.0 was set to 250.00 W from 250.00 W.

Warning: persistence mode is disabled on this device. This settings will go back to default as soon as driver unloads (e.g. last application like nvidia-smi or cuda application terminates). Run with [--help | -h] switch to get more information on how to enable persistence mode.

All done.
Traceback (most recent call last):
  File "/home/mock/rpmbuild/BUILD/minotaur-0.9.8.8/minotaur.py", line 983, in <module>
  File "/home/mock/rpmbuild/BUILD/minotaur-0.9.8.8/minotaur.py", line 617, in calibrate
  File "/home/mock/rpmbuild/BUILD/minotaur-0.9.8.8/calibrate.py", line 115, in start
  File "/home/mock/rpmbuild/BUILD/minotaur-0.9.8.8/device.py", line 199, in start
  File "/home/mock/rpmbuild/BUILD/minotaur-0.9.8.8/miners.py", line 212, in start_device
KeyError: 'ccminer2'
```

also `minotaur --algos` still shows ccminer2 in table, even though it is disabled. Should it be excluded?

**Comment by m4rkw** [comment]
0.9.8.13 should fix the crash. i don't think there's any harm in showing calibrated rates for disabled miners.
