### ISSUE TITLE
gs crashes when minotaur is restarted

### ISSUE THREAD

**Issue by biesbjerg** [m4rkw/minotaur#13]
`sudo systemctl restart minotaur` while `minotaur --gs` makes it crash.

```
Traceback (most recent call last):
  File "/home/mock/rpmbuild/BUILD/minotaur-0.9.8.8/minotaur.py", line 958, in <module>
  File "/usr/lib64/python2.7/curses/wrapper.py", line 43, in wrapper
    return func(stdscr, *args, **kwds)
  File "/home/mock/rpmbuild/BUILD/minotaur-0.9.8.8/gs.py", line 84, in gs
  File "/home/mock/rpmbuild/BUILD/minotaur-0.9.8.8/gs.py", line 449, in get_local_data
TypeError: string indices must be integers, not str
```

**Comment by m4rkw** [comment]
couldn't reproduce with the latest build, try upgrading
