### ISSUE TITLE
Calibration error - IndexError: list index out of range

### ISSUE THREAD

**Issue by biesbjerg** [m4rkw/minotaur#15]
Sometimes I get an error when calibrating:
```
@Traceback (most recent call last):
  File "/home/mock/rpmbuild/BUILD/minotaur-0.9.8.8/minotaur.py", line 983, in <module>
  File "/home/mock/rpmbuild/BUILD/minotaur-0.9.8.8/minotaur.py", line 617, in calibrate
  File "/home/mock/rpmbuild/BUILD/minotaur-0.9.8.8/calibrate.py", line 185, in start
  File "/home/mock/rpmbuild/BUILD/minotaur-0.9.8.8/calibrate.py", line 351, in do_power_calibration
  File "/home/mock/rpmbuild/BUILD/minotaur-0.9.8.8/calibrate.py", line 258, in get_max_hashrate_and_power_draw
IndexError: list index out of range
```

Full output:
```
bash-4.2$ minotaur --calibrate 2 nicehash ccminer x11gost eu --overwrite --force

------------------------------------------------------------------------------------
info: PLEASE NOTE: this process will not automatically overclock your card unless
info: you have enabled overclocking and configured a device profile with overclock
info: settings. You and you alone are responsible for any overclock settings that
info: you want to run this benchmark process with. We do not advise overclocking
info: and are not responsible for any hardware damage that may occur when using
info: this tool.
------------------------------------------------------------------------------------

info:      device id: 2
info:           pool: nicehash
info:   device class: 1080Ti
info: device profile: 1080ti_oc_x11gost
info:          miner: ccminer
info:      algorithm: x11gost
info:         region: eu
info: device 2 [1080Ti]: terminating existing worker

  Attribute 'GPUGraphicsClockOffset' (localhost.localdomain:0[gpu:2]) assigned value 0.


  Attribute 'GPUMemoryTransferRateOffset' (localhost.localdomain:0[gpu:2]) assigned value 0.

Power limit for GPU 00000000:05:00.0 was set to 250.00 W from 260.00 W.

Warning: persistence mode is disabled on this device. This settings will go back to default as soon as driver unloads (e.g. last application like nvidia-smi or cuda application terminates). Run with [--help | -h] switch to get more information on how to enable persistence mode.

All done.
info: device 2 [1080Ti]: max power limit: 300 W
info: device 2 [1080Ti]: stabilisation tolerance: 2.50%

  Attribute 'GPUGraphicsClockOffset' (localhost.localdomain:0[gpu:2]) assigned value 0.


  Attribute 'GPUMemoryTransferRateOffset' (localhost.localdomain:0[gpu:2]) assigned value 0.

Power limit for GPU 00000000:05:00.0 was set to 250.00 W from 250.00 W.

Warning: persistence mode is disabled on this device. This settings will go back to default as soon as driver unloads (e.g. last application like nvidia-smi or cuda application terminates). Run with [--help | -h] switch to get more information on how to enable persistence mode.

All done.
Power limit for GPU 00000000:05:00.0 was set to 250.00 W from 260.00 W.

Warning: persistence mode is disabled on this device. This settings will go back to default as soon as driver unloads (e.g. last application like nvidia-smi or cuda application terminates). Run with [--help | -h] switch to get more information on how to enable persistence mode.

All done.

  Attribute 'GPUGraphicsClockOffset' (localhost.localdomain:0[gpu:2]) assigned value 125.


  Attribute 'GPUMemoryTransferRateOffset' (localhost.localdomain:0[gpu:2]) assigned value 750.

Power limit for GPU 00000000:05:00.0 was set to 260.00 W from 250.00 W.

Warning: persistence mode is disabled on this device. This settings will go back to default as soon as driver unloads (e.g. last application like nvidia-smi or cuda application terminates). Run with [--help | -h] switch to get more information on how to enable persistence mode.

All done.
info: device 2 [1080Ti]: starting warmup cycle at max power limit [timeout=15mins]
Power limit for GPU 00000000:05:00.0 was set to 300.00 W from 260.00 W.

Warning: persistence mode is disabled on this device. This settings will go back to default as soon as driver unloads (e.g. last application like nvidia-smi or cuda application terminates). Run with [--help | -h] switch to get more information on how to enable persistence mode.

All done.
info: device 2 [1080Ti]: hashrate: 15.93 MH/s
info: device 2 [1080Ti]: hashrate: 17.47 MH/s (variance 9.67%)
info: device 2 [1080Ti]: hashrate: 17.52 MH/s (variance 9.98%)
info: device 2 [1080Ti]: hashrate: 17.52 MH/s (variance 9.98%)
info: device 2 [1080Ti]: hashrate: 17.51 MH/s (variance 9.98%)
info: device 2 [1080Ti]: hashrate: 17.37 MH/s (variance 0.86%)
info: device 2 [1080Ti]: hashrate stabilised
info: device 2 [1080Ti]: warmup cycle complete
info: device 2 [1080Ti]: warmup hashrate: 17.45 MH/s
info: device 2 [1080Ti]: max power draw: 275.42
info: device 2 [1080Ti]: starting initial run at max power limit [timeout=15mins]
Power limit for GPU 00000000:05:00.0 was set to 250.00 W from 260.00 W.

Warning: persistence mode is disabled on this device. This settings will go back to default as soon as driver unloads (e.g. last application like nvidia-smi or cuda application terminates). Run with [--help | -h] switch to get more information on how to enable persistence mode.

All done.
^@
  Attribute 'GPUGraphicsClockOffset' (localhost.localdomain:0[gpu:2]) assigned value 125.


  Attribute 'GPUMemoryTransferRateOffset' (localhost.localdomain:0[gpu:2]) assigned value 750.

Power limit for GPU 00000000:05:00.0 was set to 260.00 W from 250.00 W.

Warning: persistence mode is disabled on this device. This settings will go back to default as soon as driver unloads (e.g. last application like nvidia-smi or cuda application terminates). Run with [--help | -h] switch to get more information on how to enable persistence mode.

All done.
Power limit for GPU 00000000:05:00.0 was set to 300.00 W from 260.00 W.

Warning: persistence mode is disabled on this device. This settings will go back to default as soon as driver unloads (e.g. last application like nvidia-smi or cuda application terminates). Run with [--help | -h] switch to get more information on how to enable persistence mode.

All done.
info: device 2 [1080Ti]: hashrate: 11.55 MH/s
info: device 2 [1080Ti]: hashrate: 11.55 MH/s (variance 0.00%)
info: device 2 [1080Ti]: hashrate: 17.47 MH/s (variance 51.26%)
info: device 2 [1080Ti]: hashrate: 17.47 MH/s (variance 51.26%)
info: device 2 [1080Ti]: hashrate: 17.49 MH/s (variance 51.43%)
^@info: device 2 [1080Ti]: hashrate: 17.49 MH/s (variance 51.43%)
info: device 2 [1080Ti]: hashrate: 17.50 MH/s (variance 0.17%)
info: device 2 [1080Ti]: hashrate stabilised
info: device 2 [1080Ti]: benchmark hashrate: 17.48 MH/s
info: device 2 [1080Ti]: max power draw: 267.72
info: device 2 [1080Ti]: tuning power limit for optimum efficiency
info: device 2 [1080Ti]: setting power limit: 268 W
Power limit for GPU 00000000:05:00.0 was set to 268.00 W from 260.00 W.

Warning: persistence mode is disabled on this device. This settings will go back to default as soon as driver unloads (e.g. last application like nvidia-smi or cuda application terminates). Run with [--help | -h] switch to get more information on how to enable persistence mode.

All done.
info: device 2 [1080Ti]: hashrate: 17.50 MH/s
info: device 2 [1080Ti]: hashrate: 17.49 MH/s (variance 0.06%)
info: device 2 [1080Ti]: hashrate: 17.49 MH/s (variance 0.06%)
^@info: device 2 [1080Ti]: hashrate: 17.54 MH/s (variance 0.29%)
info: device 2 [1080Ti]: hashrate: 17.40 MH/s (variance 0.80%)
info: device 2 [1080Ti]: hashrate stabilised
info: device 2 [1080Ti]: nominal hashrate: 17.47 MH/s
info: device 2 [1080Ti]: hashrate loss is within acceptable 1.00%, continuing
info: device 2 [1080Ti]: setting power limit: 266 W
Power limit for GPU 00000000:05:00.0 was set to 266.00 W from 260.00 W.

Warning: persistence mode is disabled on this device. This settings will go back to default as soon as driver unloads (e.g. last application like nvidia-smi or cuda application terminates). Run with [--help | -h] switch to get more information on how to enable persistence mode.

All done.
info: device 2 [1080Ti]: hashrate: 17.40 MH/s
info: device 2 [1080Ti]: hashrate: 17.45 MH/s (variance 0.29%)
info: device 2 [1080Ti]: hashrate: 17.20 MH/s (variance 1.45%)
^@info: device 2 [1080Ti]: hashrate: 17.20 MH/s (variance 1.45%)
info: device 2 [1080Ti]: hashrate: 17.20 MH/s (variance 1.45%)
info: device 2 [1080Ti]: hashrate stabilised
info: device 2 [1080Ti]: nominal hashrate: 17.32 MH/s
info: device 2 [1080Ti]: hashrate loss is within acceptable 1.00%, continuing
info: device 2 [1080Ti]: setting power limit: 264 W
Power limit for GPU 00000000:05:00.0 was set to 264.00 W from 260.00 W.

Warning: persistence mode is disabled on this device. This settings will go back to default as soon as driver unloads (e.g. last application like nvidia-smi or cuda application terminates). Run with [--help | -h] switch to get more information on how to enable persistence mode.

All done.
info: device 2 [1080Ti]: hashrate: 17.20 MH/s
info: device 2 [1080Ti]: hashrate: 17.28 MH/s (variance 0.47%)
info: device 2 [1080Ti]: hashrate: 17.38 MH/s (variance 1.05%)
^@info: device 2 [1080Ti]: hashrate: 17.38 MH/s (variance 1.05%)
info: device 2 [1080Ti]: hashrate: 17.64 MH/s (variance 2.56%)
info: device 2 [1080Ti]: hashrate: 17.64 MH/s (variance 2.08%)
info: device 2 [1080Ti]: hashrate stabilised
info: device 2 [1080Ti]: nominal hashrate: 17.46 MH/s
info: device 2 [1080Ti]: hashrate loss is within acceptable 1.00%, continuing
info: device 2 [1080Ti]: setting power limit: 262 W
Power limit for GPU 00000000:05:00.0 was set to 262.00 W from 260.00 W.

Warning: persistence mode is disabled on this device. This settings will go back to default as soon as driver unloads (e.g. last application like nvidia-smi or cuda application terminates). Run with [--help | -h] switch to get more information on how to enable persistence mode.

All done.
info: device 2 [1080Ti]: hashrate: 17.64 MH/s
info: device 2 [1080Ti]: hashrate: 17.54 MH/s (variance 0.57%)
^@Traceback (most recent call last):
  File "/home/mock/rpmbuild/BUILD/minotaur-0.9.8.8/minotaur.py", line 983, in <module>
  File "/home/mock/rpmbuild/BUILD/minotaur-0.9.8.8/minotaur.py", line 617, in calibrate
  File "/home/mock/rpmbuild/BUILD/minotaur-0.9.8.8/calibrate.py", line 185, in start
  File "/home/mock/rpmbuild/BUILD/minotaur-0.9.8.8/calibrate.py", line 351, in do_power_calibration
  File "/home/mock/rpmbuild/BUILD/minotaur-0.9.8.8/calibrate.py", line 258, in get_max_hashrate_and_power_draw
IndexError: list index out of range
```

**Comment by m4rkw** [comment]
should be fixed in the latest release
