### ISSUE TITLE
excavator:daggerhashimoto on coinotron crashes minotaur

### ISSUE THREAD

**Issue by gordan-bobic** [m4rkw/minotaur#17]
Both --mine and --gs crash after the jobs are correctly set up:

```
  coinotron:
    enable: true
    shortname: ct
    endpoints:
      - coinotron.com:3344
    algorithm: daggerhashimoto
    miners:
    - excavator
    whattomine_coin_no: 151
    user: "username"
    worker_name: "worker:password"
    append_device_id_to_worker_name: false
    timeout: 3
    pool_fee: 2
```

mine:
```
Traceback (most recent call last):
  File "/home/mock/rpmbuild/BUILD/minotaur-1.1.2/minotaur.py", line 1022, in <module>
  File "/home/mock/rpmbuild/BUILD/minotaur-1.1.2/minotaur.py", line 284, in run
  File "/home/mock/rpmbuild/BUILD/minotaur-1.1.2/device.py", line 139, in update
  File "/home/mock/rpmbuild/BUILD/minotaur-1.1.2/miners.py", line 95, in get_device_state
```

gs:
```
Traceback (most recent call last):
  File "/home/mock/rpmbuild/BUILD/minotaur-1.1.2/minotaur.py", line 971, in <module>
  File "/usr/lib64/python2.7/curses/wrapper.py", line 43, in wrapper
    return func(stdscr, *args, **kwds)
  File "/home/mock/rpmbuild/BUILD/minotaur-1.1.2/gs.py", line 87, in gs
  File "/home/mock/rpmbuild/BUILD/minotaur-1.1.2/gs.py", line 303, in get_local_data
  File "/home/mock/rpmbuild/BUILD/minotaur-1.1.2/miners.py", line 95, in get_device_state
ValueError: too many values to unpack
```

**Comment by gordan-bobic** [comment]
Turns out, you cannot specify a password, it is assumed to be "x".
