### ISSUE TITLE
Error when disabling algorithm

### ISSUE THREAD

**Issue by biesbjerg** [m4rkw/minotaur#23]
If you comment out an algorithm in minotaur.conf, you get the following error when starting `--mine`:
```
Traceback (most recent call last):
  File "/home/miner/minotaur-src/minotaur.py", line 1084, in <module>
  File "/home/miner/minotaur-src/minotaur.py", line 305, in run
  File "/home/miner/minotaur-src/pools.py", line 54, in refresh
  File "/home/miner/minotaur-src/calibration.py", line 218, in get_best_hashrates
KeyError: 'neoscrypt'
```

**Comment by m4rkw** [comment]
should be fixed in 1.0.4
