### ISSUE TITLE
Calibration file suddenly empty

### ISSUE THREAD

**Issue by biesbjerg** [m4rkw/minotaur#26]
After rebooting a bunch of times, related to rig maintenance, minotaur suddenly wouldn't start mining.

```
  /--------------------------/
 / minotaur 1.0.10 by m4rkw /
/--------------------------/

info: initialising
info: new version available: v1.0.11
info: scanning devices
info: found 6 nvidia GPUs
info: donation level: 1%
info: device 0 [1080Ti]:   ccminer: blake2s,blake256r8,decred,cryptonight,x13,keccak,x11gost,neoscrypt
info: device 0 [1080Ti]:   ccminer: quark,nist5,qubit,skunk,lbry,lyra2rev2,x15
info: device 0 [1080Ti]:  ethminer: daggerhashimoto
info: device 0 [1080Ti]: excavator: blake2s,daggerhashimoto_sia,cryptonight,daggerhashimoto,keccak
info: device 0 [1080Ti]: excavator: sia,neoscrypt,daggerhashimoto_decred,daggerhashimoto_pascal,pascal
info: device 0 [1080Ti]: excavator: decred,nist5,equihash,lbry,lyra2rev2
info: device 0 [1080Ti]:  ccminer2: blake2s,keccak,quark,x11gost,qubit,lbry,nist5
info: device 1 [1080Ti]:  as above
info: device 2 [1080Ti]:  as above
info: device 3 [1080Ti]:  as above
info: device 4 [1080Ti]:  as above
info: device 5 [1080Ti]:  as above
info: you have calibration data for all supported algorithms :)
info: retrieving state from miner backends
Traceback (most recent call last):
  File "/home/mock/rpmbuild/BUILD/minotaur-1.0.10/minotaur.py", line 1087, in <module>
  File "/home/mock/rpmbuild/BUILD/minotaur-1.0.10/minotaur.py", line 286, in run
  File "/home/mock/rpmbuild/BUILD/minotaur-1.0.10/minotaur.py", line 187, in initialise
  File "/home/mock/rpmbuild/BUILD/minotaur-1.0.10/minotaur.py", line 275, in scan_devices
  File "/home/mock/rpmbuild/BUILD/minotaur-1.0.10/device.py", line 121, in update
  File "/home/mock/rpmbuild/BUILD/minotaur-1.0.10/device.py", line 104, in update_bests
  File "/home/mock/rpmbuild/BUILD/minotaur-1.0.10/pools.py", line 143, in get_most_profitable_action
  File "/home/mock/rpmbuild/BUILD/minotaur-1.0.10/ethermine.py", line 104, in get_best_miner_and_algorithm
  File "/home/mock/rpmbuild/BUILD/minotaur-1.0.10/calibration.py", line 194, in get_best_algorithm_benchmarks
TypeError: 'NoneType' object has no attribute '__getitem__'
```

A calibration file was suddenly empty (my guess is the one that was mining while rebooting).

Maybe a race condition is possible somewhere, where dynamic adjusted hashrates is not always written to file in case of server reboots etc?

**Comment by m4rkw** [comment]
i haven't been able to find an explanation for this in the code
