### ISSUE TITLE
stats: list index out of range

### ISSUE THREAD

**Issue by biesbjerg** [m4rkw/minotaur#29]
```
[midas@midas ~]$ stats

stats for the last 24 hours:

Traceback (most recent call last):
  File "/home/miner/minotaur-src/minotaur.py", line 1022, in <module>
  File "/home/miner/minotaur-src/minotaur.py", line 795, in stats
  File "/home/miner/minotaur-src/stats.py", line 83, in get_logs_for_period
IndexError: list index out of range
```

[minotaur.csv.zip](https://github.com/m4rkw/minotaur/files/1757733/minotaur.csv.zip)

**Comment by m4rkw** [comment]
should be fixed in the next release
