### ISSUE TITLE
minotaur --gs doesn't exit cleanly on CTRL+C

### ISSUE THREAD

**Issue by biesbjerg** [m4rkw/minotaur#6]
When running `minotaur --gs` and pressing `CTRL+C` to exit, the following is printed before exiting:

```
Traceback (most recent call last):
  File "/home/mock/rpmbuild/BUILD/minotaur-0.9.8.3/minotaur.py", line 916, in <module>
  File "/usr/lib64/python2.7/curses/wrapper.py", line 43, in wrapper
    return func(stdscr, *args, **kwds)
  File "/home/mock/rpmbuild/BUILD/minotaur-0.9.8.3/gs.py", line 79, in gs
  File "/home/mock/rpmbuild/BUILD/minotaur-0.9.8.3/gs.py", line 239, in get_local_data
  File "/home/mock/rpmbuild/BUILD/minotaur-0.9.8.3/nvidia.py", line 60, in get_nvidia_devices
KeyboardInterrupt
```

**Comment by m4rkw** [comment]
fixed in master
